package utils

import (
	"bytes"
	"crypto"
	"encoding/base64"
	"errors"
	"fmt"
	"github.com/michaelsauter/ocdiff/cli"
	"golang.org/x/crypto/openpgp"
	"golang.org/x/crypto/openpgp/armor"
	"golang.org/x/crypto/openpgp/packet"
	"io"
	"io/ioutil"
	"os"
	"strings"
)

func CreateEntity(name, email string) (*openpgp.Entity, error) {
	var e *openpgp.Entity
	conf := &packet.Config{
		RSABits:       4096,
		DefaultHash:   crypto.SHA256,
		DefaultCipher: packet.CipherFunction(packet.CipherAES128),
	}
	e, err := openpgp.NewEntity(name, "Generated by ocdiff", email, conf)
	if err != nil {
		return nil, err
	}

	// Sign all the identities
	for _, id := range e.Identities {
		err := id.SelfSignature.SignUserId(id.UserId.Id, e.PrimaryKey, e.PrivateKey, nil)
		if err != nil {
			return nil, err
		}
	}
	return e, nil
}

func PrintPublicKey(entity *openpgp.Entity, filename string) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	w, err := armor.Encode(f, openpgp.PublicKeyType, nil)
	if err != nil {
		return err
	}
	entity.Serialize(w)
	w.Close()
	io.WriteString(f, "\n")
	return nil
}

func PrintPrivateKey(entity *openpgp.Entity, filename string) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	w, err := armor.Encode(f, openpgp.PrivateKeyType, nil)
	if err != nil {
		return err
	}
	entity.SerializePrivate(w, nil)
	w.Close()
	io.WriteString(f, "\n")
	return nil
}

// Assembles entity list from keys in given files
func GetEntityList(keys []string) (openpgp.EntityList, error) {
	cli.VerboseMsg("Assemble entity list from", strings.Join(keys, ","))
	entityList := openpgp.EntityList{}
	for _, filename := range keys {
		keyringFileBuffer, _ := os.Open(filename)
		defer keyringFileBuffer.Close()
		l, err := openpgp.ReadArmoredKeyRing(keyringFileBuffer)
		if err != nil {
			return entityList, errors.New(
				fmt.Sprintf("Reading key '%s' failed: %s", filename, err),
			)
		}
		entityList = append(entityList, l[0])
	}
	return entityList, nil
}

// Encrypts secret with all public keys and base64-encodes the result.
func Encrypt(secret string, entityList openpgp.EntityList) (string, error) {
	// Encrypt message using public keys
	buf := new(bytes.Buffer)
	w, err := openpgp.Encrypt(buf, entityList, nil, nil, nil)
	if err != nil {
		return "", errors.New(
			fmt.Sprintf("Encrypting '%s' failed: %s", secret, err),
		)
	}
	_, err = w.Write([]byte(secret))
	if err != nil {
		return "", err
	}
	err = w.Close()
	if err != nil {
		return "", err
	}

	// Return as base64 encoded string
	bytes, err := ioutil.ReadAll(buf)
	if err != nil {
		return "", err
	}
	str := base64.StdEncoding.EncodeToString(bytes)
	return str, nil
}

// Decrypts the base64-encoded string end decrypts with the private key.
func Decrypt(encoded string, entityList openpgp.EntityList) (string, error) {
	// Decode bas64-encoded string
	encrypted, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return "", errors.New(
			fmt.Sprintf("Decoding '%s' failed: %s", encoded, err),
		)
	}

	// Decrypt encrypted message
	buf := bytes.NewBuffer([]byte(encrypted))
	md, err := openpgp.ReadMessage(buf, entityList, nil, nil)
	if err != nil {
		return "", errors.New(
			fmt.Sprintf("Decrypting '%s' failed: %s", encoded, err),
		)
	}
	bytes, err := ioutil.ReadAll(md.UnverifiedBody)
	return string(bytes), err
}
