name: Continous Integration Tests
on: [push, pull_request]
jobs:
  tailor:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      -
        name: Download Go tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
          go install golang.org/x/tools/cmd/goimports@latest
          echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
      -
        name: Run lint
        run: |
          make lint
      -
        name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.4
        timeout-minutes: 5
        with:
          oc version: 'v3.11.0'
          enable: 'centos-imagestreams,persistent-volumes,registry,router'
          github token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run tests
        run: |
          sudo chown -R runner:docker openshift.local.clusterup/
          make test
